import { FilterProfile, FiltersPayload } from './models';

/**
 * Plan-shaped GET /api/filters fixture (FILTERS_API_PLAN + mockup scenario).
 * Served only when FILTERS_MOCK_FALLBACK_ENABLED and GET returns 404.
 * TODO(filters-api): delete with the fallback flag once the endpoint is live.
 * Lists are abbreviated; shapes and merge/meta match the contract.
 */
const DEFAULTS: FilterProfile = {
  title_keywords: ['angular', 'frontend', 'front-end', 'javascript', 'typescript'],
  require_title_terms: [],
  exclude_levels: [
    'junior',
    'intern',
    'internship',
    'trainee',
    'stażysta',
    'praktykant',
    'staz',
    'tech lead',
    'tech-lead',
    'techlead',
    'техлид',
    'team lead',
    'тимлид',
    'project lead',
    'engineering manager',
    'head of engineering',
    'vp of engineering',
    'cto',
    'part-time',
    'part time',
    'parttime',
  ],
  exclude_patterns: [
    '\\bjava\\b',
    '\\.net',
    '\\bphp\\b',
    '\\bqa\\b',
    '\\bvue\\b',
    '\\bwordpress\\b',
    '\\bdrupal\\b',
    '\\bmagento\\b',
    '\\bsharepoint\\b',
  ],
  exclude_stacks_without: { unless: 'angular', block: ['react'] },
  exclude_fullstack_with_backend: true,
  fullstack_backend_stacks: [
    '\\bjava\\b',
    '\\bspring(?:\\s+boot)?\\b',
    '\\.net\\b',
    '\\bpython\\b',
    '\\bgolang\\b',
  ],
  exclude_body_disqualifiers: true,
  body_exclude_patterns: [
    '\\bblazor\\b',
    '\\bmendix\\b',
    '\\boutsystems\\b',
    '\\blow[-\\s]?code\\b',
    '\\bwordpress\\b',
    '\\bdrupal\\b',
    '\\bmagento\\b',
    '\\bsharepoint\\b',
  ],
  exclude_body_onsite_city: true,
  allow_low_frequency_hybrid: true,
  exclude_german_language_required: true,
  exclude_unacceptable_contract: true,
  exclude_relocation_required: true,
  exclude_ai_training: true,
  exclude_companies: ['micro1', 'alignerr', 'quikhire', 'hirefeed', 'mercor', 'outlier ai'],
  extra_anti_hybrid_cities: [
    'berlin',
    'helsinki',
    'barcelona',
    'limassol',
    'bangalore',
    'munich',
    'amsterdam',
    'prague',
    'singapore',
    'dubai',
  ],
  locations: ['remote', 'zdalnie', 'zdalna', 'wrocław', 'wroclaw'],
  languages: ['english', 'polish', 'russian', 'german'],
  home_city: 'Wrocław',
};

/** Mockup scenario: React developer who overrode a few knobs. */
export const FILTERS_MOCK_PAYLOAD: FiltersPayload = {
  defaults: DEFAULTS,
  overrides: {
    title_keywords: ['react', 'frontend', 'front-end', 'javascript', 'typescript'],
    exclude_patterns: ['\\bjava\\b', '\\bphp\\b', '\\bangular\\b', '\\bwordpress\\b', '\\bqa\\b'],
    exclude_german_language_required: false,
    exclude_companies: [
      'micro1',
      'alignerr',
      'quikhire',
      'hirefeed',
      'mercor',
      'outlier ai',
      'local-staffing-co',
    ],
    extra_anti_hybrid_cities: [
      'berlin',
      'helsinki',
      'barcelona',
      'limassol',
      'bangalore',
      'munich',
      'amsterdam',
      'prague',
      'singapore',
      'dubai',
      'poznań',
    ],
  },
  effective: {
    ...DEFAULTS,
    title_keywords: ['react', 'frontend', 'front-end', 'javascript', 'typescript'],
    exclude_patterns: ['\\bjava\\b', '\\bphp\\b', '\\bangular\\b', '\\bwordpress\\b', '\\bqa\\b'],
    exclude_german_language_required: false,
    exclude_companies: [
      'micro1',
      'alignerr',
      'quikhire',
      'hirefeed',
      'mercor',
      'outlier ai',
      'local-staffing-co',
    ],
    extra_anti_hybrid_cities: [
      'berlin',
      'helsinki',
      'barcelona',
      'limassol',
      'bangalore',
      'munich',
      'amsterdam',
      'prague',
      'singapore',
      'dubai',
      'poznań',
    ],
  },
  meta: {
    title_keywords: { type: 'string_list', merge: 'replace' },
    require_title_terms: { type: 'string_list', merge: 'replace' },
    exclude_levels: { type: 'string_list', merge: 'replace' },
    exclude_patterns: { type: 'pattern_list', merge: 'replace' },
    exclude_stacks_without: { type: 'stacks_without', merge: 'replace' },
    exclude_fullstack_with_backend: { type: 'boolean', merge: 'replace' },
    fullstack_backend_stacks: { type: 'pattern_list', merge: 'replace' },
    exclude_body_disqualifiers: { type: 'boolean', merge: 'replace' },
    body_exclude_patterns: { type: 'pattern_list', merge: 'replace' },
    exclude_body_onsite_city: { type: 'boolean', merge: 'replace' },
    allow_low_frequency_hybrid: { type: 'boolean', merge: 'replace' },
    exclude_german_language_required: { type: 'boolean', merge: 'replace' },
    exclude_unacceptable_contract: { type: 'boolean', merge: 'replace' },
    exclude_relocation_required: { type: 'boolean', merge: 'replace' },
    exclude_ai_training: { type: 'boolean', merge: 'replace' },
    exclude_companies: { type: 'string_list', merge: 'extend_only' },
    extra_anti_hybrid_cities: { type: 'string_list', merge: 'extend_only' },
    locations: { type: 'string_list', derived: 'candidate.yaml' },
    languages: { type: 'string_list', derived: 'candidate.yaml' },
    home_city: { type: 'string', derived: 'candidate.yaml' },
  },
};

export function cloneFiltersMock(): FiltersPayload {
  return structuredClone(FILTERS_MOCK_PAYLOAD);
}
